name: Building # Nombre del workflow
on: [push] # Cuando se ejecuta
jobs: # Solo vamos a crear uno
  building:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # Copiamos el repositorio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Poetry 
        uses: snok/install-poetry@v1
      - run: poetry build # Ejecuto un comando de consola en el repo.
      - name: Publish to GH Releases
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.workspace }}/dist/*